/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicsIndexRouteImport } from './routes/topics/index'
import { Route as TopicsTopicRouteImport } from './routes/topics/$topic'
import { Route as ApiTopicsRouteImport } from './routes/api/topics'
import { Route as ApiOverviewRouteImport } from './routes/api/overview'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiAdrsRouteImport } from './routes/api/adrs'
import { Route as ApiIndexIndexRouteImport } from './routes/api/index/index'
import { Route as TopicsTopicReceiptsRouteImport } from './routes/topics/$topic/receipts'
import { Route as TopicsTopicHealthRouteImport } from './routes/topics/$topic/health'
import { Route as TopicsTopicGraphRouteImport } from './routes/topics/$topic/graph'
import { Route as TopicsTopicFactsRouteImport } from './routes/topics/$topic/facts'
import { Route as TopicsTopicEvidenceRouteImport } from './routes/topics/$topic/evidence'
import { Route as ApiTopicsTopicRouteImport } from './routes/api/topics/$topic'
import { Route as ApiEventsStatusRouteImport } from './routes/api/events/status'
import { Route as ApiAdrsIdRouteImport } from './routes/api/adrs/$id'
import { Route as TopicsTopicDocumentsKindRouteImport } from './routes/topics/$topic/documents/$kind'
import { Route as ApiTopicsTopicGraphRouteImport } from './routes/api/topics/$topic/graph'
import { Route as ApiTopicsTopicEvidenceRouteImport } from './routes/api/topics/$topic/evidence'
import { Route as ApiTopicsTopicDocsRouteImport } from './routes/api/topics/$topic/docs'
import { Route as ApiTopicsTopicDocsKindRouteImport } from './routes/api/topics/$topic/docs/$kind'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicRoute = TopicsTopicRouteImport.update({
  id: '/topics/$topic',
  path: '/topics/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTopicsRoute = ApiTopicsRouteImport.update({
  id: '/api/topics',
  path: '/api/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOverviewRoute = ApiOverviewRouteImport.update({
  id: '/api/overview',
  path: '/api/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdrsRoute = ApiAdrsRouteImport.update({
  id: '/api/adrs',
  path: '/api/adrs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndexIndexRoute = ApiIndexIndexRouteImport.update({
  id: '/api/index/',
  path: '/api/index/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicReceiptsRoute = TopicsTopicReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => TopicsTopicRoute,
} as any)
const TopicsTopicHealthRoute = TopicsTopicHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => TopicsTopicRoute,
} as any)
const TopicsTopicGraphRoute = TopicsTopicGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => TopicsTopicRoute,
} as any)
const TopicsTopicFactsRoute = TopicsTopicFactsRouteImport.update({
  id: '/facts',
  path: '/facts',
  getParentRoute: () => TopicsTopicRoute,
} as any)
const TopicsTopicEvidenceRoute = TopicsTopicEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => TopicsTopicRoute,
} as any)
const ApiTopicsTopicRoute = ApiTopicsTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => ApiTopicsRoute,
} as any)
const ApiEventsStatusRoute = ApiEventsStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiEventsRoute,
} as any)
const ApiAdrsIdRoute = ApiAdrsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdrsRoute,
} as any)
const TopicsTopicDocumentsKindRoute =
  TopicsTopicDocumentsKindRouteImport.update({
    id: '/documents/$kind',
    path: '/documents/$kind',
    getParentRoute: () => TopicsTopicRoute,
  } as any)
const ApiTopicsTopicGraphRoute = ApiTopicsTopicGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => ApiTopicsTopicRoute,
} as any)
const ApiTopicsTopicEvidenceRoute = ApiTopicsTopicEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => ApiTopicsTopicRoute,
} as any)
const ApiTopicsTopicDocsRoute = ApiTopicsTopicDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => ApiTopicsTopicRoute,
} as any)
const ApiTopicsTopicDocsKindRoute = ApiTopicsTopicDocsKindRouteImport.update({
  id: '/$kind',
  path: '/$kind',
  getParentRoute: () => ApiTopicsTopicDocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/adrs': typeof ApiAdrsRouteWithChildren
  '/api/events': typeof ApiEventsRouteWithChildren
  '/api/files': typeof ApiFilesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/overview': typeof ApiOverviewRoute
  '/api/topics': typeof ApiTopicsRouteWithChildren
  '/topics/$topic': typeof TopicsTopicRouteWithChildren
  '/topics/': typeof TopicsIndexRoute
  '/api/adrs/$id': typeof ApiAdrsIdRoute
  '/api/events/status': typeof ApiEventsStatusRoute
  '/api/topics/$topic': typeof ApiTopicsTopicRouteWithChildren
  '/topics/$topic/evidence': typeof TopicsTopicEvidenceRoute
  '/topics/$topic/facts': typeof TopicsTopicFactsRoute
  '/topics/$topic/graph': typeof TopicsTopicGraphRoute
  '/topics/$topic/health': typeof TopicsTopicHealthRoute
  '/topics/$topic/receipts': typeof TopicsTopicReceiptsRoute
  '/api/index/': typeof ApiIndexIndexRoute
  '/api/topics/$topic/docs': typeof ApiTopicsTopicDocsRouteWithChildren
  '/api/topics/$topic/evidence': typeof ApiTopicsTopicEvidenceRoute
  '/api/topics/$topic/graph': typeof ApiTopicsTopicGraphRoute
  '/topics/$topic/documents/$kind': typeof TopicsTopicDocumentsKindRoute
  '/api/topics/$topic/docs/$kind': typeof ApiTopicsTopicDocsKindRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/adrs': typeof ApiAdrsRouteWithChildren
  '/api/events': typeof ApiEventsRouteWithChildren
  '/api/files': typeof ApiFilesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/overview': typeof ApiOverviewRoute
  '/api/topics': typeof ApiTopicsRouteWithChildren
  '/topics/$topic': typeof TopicsTopicRouteWithChildren
  '/topics': typeof TopicsIndexRoute
  '/api/adrs/$id': typeof ApiAdrsIdRoute
  '/api/events/status': typeof ApiEventsStatusRoute
  '/api/topics/$topic': typeof ApiTopicsTopicRouteWithChildren
  '/topics/$topic/evidence': typeof TopicsTopicEvidenceRoute
  '/topics/$topic/facts': typeof TopicsTopicFactsRoute
  '/topics/$topic/graph': typeof TopicsTopicGraphRoute
  '/topics/$topic/health': typeof TopicsTopicHealthRoute
  '/topics/$topic/receipts': typeof TopicsTopicReceiptsRoute
  '/api/index': typeof ApiIndexIndexRoute
  '/api/topics/$topic/docs': typeof ApiTopicsTopicDocsRouteWithChildren
  '/api/topics/$topic/evidence': typeof ApiTopicsTopicEvidenceRoute
  '/api/topics/$topic/graph': typeof ApiTopicsTopicGraphRoute
  '/topics/$topic/documents/$kind': typeof TopicsTopicDocumentsKindRoute
  '/api/topics/$topic/docs/$kind': typeof ApiTopicsTopicDocsKindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/adrs': typeof ApiAdrsRouteWithChildren
  '/api/events': typeof ApiEventsRouteWithChildren
  '/api/files': typeof ApiFilesRoute
  '/api/health': typeof ApiHealthRoute
  '/api/overview': typeof ApiOverviewRoute
  '/api/topics': typeof ApiTopicsRouteWithChildren
  '/topics/$topic': typeof TopicsTopicRouteWithChildren
  '/topics/': typeof TopicsIndexRoute
  '/api/adrs/$id': typeof ApiAdrsIdRoute
  '/api/events/status': typeof ApiEventsStatusRoute
  '/api/topics/$topic': typeof ApiTopicsTopicRouteWithChildren
  '/topics/$topic/evidence': typeof TopicsTopicEvidenceRoute
  '/topics/$topic/facts': typeof TopicsTopicFactsRoute
  '/topics/$topic/graph': typeof TopicsTopicGraphRoute
  '/topics/$topic/health': typeof TopicsTopicHealthRoute
  '/topics/$topic/receipts': typeof TopicsTopicReceiptsRoute
  '/api/index/': typeof ApiIndexIndexRoute
  '/api/topics/$topic/docs': typeof ApiTopicsTopicDocsRouteWithChildren
  '/api/topics/$topic/evidence': typeof ApiTopicsTopicEvidenceRoute
  '/api/topics/$topic/graph': typeof ApiTopicsTopicGraphRoute
  '/topics/$topic/documents/$kind': typeof TopicsTopicDocumentsKindRoute
  '/api/topics/$topic/docs/$kind': typeof ApiTopicsTopicDocsKindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/adrs'
    | '/api/events'
    | '/api/files'
    | '/api/health'
    | '/api/overview'
    | '/api/topics'
    | '/topics/$topic'
    | '/topics/'
    | '/api/adrs/$id'
    | '/api/events/status'
    | '/api/topics/$topic'
    | '/topics/$topic/evidence'
    | '/topics/$topic/facts'
    | '/topics/$topic/graph'
    | '/topics/$topic/health'
    | '/topics/$topic/receipts'
    | '/api/index/'
    | '/api/topics/$topic/docs'
    | '/api/topics/$topic/evidence'
    | '/api/topics/$topic/graph'
    | '/topics/$topic/documents/$kind'
    | '/api/topics/$topic/docs/$kind'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/adrs'
    | '/api/events'
    | '/api/files'
    | '/api/health'
    | '/api/overview'
    | '/api/topics'
    | '/topics/$topic'
    | '/topics'
    | '/api/adrs/$id'
    | '/api/events/status'
    | '/api/topics/$topic'
    | '/topics/$topic/evidence'
    | '/topics/$topic/facts'
    | '/topics/$topic/graph'
    | '/topics/$topic/health'
    | '/topics/$topic/receipts'
    | '/api/index'
    | '/api/topics/$topic/docs'
    | '/api/topics/$topic/evidence'
    | '/api/topics/$topic/graph'
    | '/topics/$topic/documents/$kind'
    | '/api/topics/$topic/docs/$kind'
  id:
    | '__root__'
    | '/'
    | '/api/adrs'
    | '/api/events'
    | '/api/files'
    | '/api/health'
    | '/api/overview'
    | '/api/topics'
    | '/topics/$topic'
    | '/topics/'
    | '/api/adrs/$id'
    | '/api/events/status'
    | '/api/topics/$topic'
    | '/topics/$topic/evidence'
    | '/topics/$topic/facts'
    | '/topics/$topic/graph'
    | '/topics/$topic/health'
    | '/topics/$topic/receipts'
    | '/api/index/'
    | '/api/topics/$topic/docs'
    | '/api/topics/$topic/evidence'
    | '/api/topics/$topic/graph'
    | '/topics/$topic/documents/$kind'
    | '/api/topics/$topic/docs/$kind'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAdrsRoute: typeof ApiAdrsRouteWithChildren
  ApiEventsRoute: typeof ApiEventsRouteWithChildren
  ApiFilesRoute: typeof ApiFilesRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiOverviewRoute: typeof ApiOverviewRoute
  ApiTopicsRoute: typeof ApiTopicsRouteWithChildren
  TopicsTopicRoute: typeof TopicsTopicRouteWithChildren
  TopicsIndexRoute: typeof TopicsIndexRoute
  ApiIndexIndexRoute: typeof ApiIndexIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topic': {
      id: '/topics/$topic'
      path: '/topics/$topic'
      fullPath: '/topics/$topic'
      preLoaderRoute: typeof TopicsTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/topics': {
      id: '/api/topics'
      path: '/api/topics'
      fullPath: '/api/topics'
      preLoaderRoute: typeof ApiTopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/overview': {
      id: '/api/overview'
      path: '/api/overview'
      fullPath: '/api/overview'
      preLoaderRoute: typeof ApiOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/adrs': {
      id: '/api/adrs'
      path: '/api/adrs'
      fullPath: '/api/adrs'
      preLoaderRoute: typeof ApiAdrsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/index/': {
      id: '/api/index/'
      path: '/api/index'
      fullPath: '/api/index/'
      preLoaderRoute: typeof ApiIndexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topic/receipts': {
      id: '/topics/$topic/receipts'
      path: '/receipts'
      fullPath: '/topics/$topic/receipts'
      preLoaderRoute: typeof TopicsTopicReceiptsRouteImport
      parentRoute: typeof TopicsTopicRoute
    }
    '/topics/$topic/health': {
      id: '/topics/$topic/health'
      path: '/health'
      fullPath: '/topics/$topic/health'
      preLoaderRoute: typeof TopicsTopicHealthRouteImport
      parentRoute: typeof TopicsTopicRoute
    }
    '/topics/$topic/graph': {
      id: '/topics/$topic/graph'
      path: '/graph'
      fullPath: '/topics/$topic/graph'
      preLoaderRoute: typeof TopicsTopicGraphRouteImport
      parentRoute: typeof TopicsTopicRoute
    }
    '/topics/$topic/facts': {
      id: '/topics/$topic/facts'
      path: '/facts'
      fullPath: '/topics/$topic/facts'
      preLoaderRoute: typeof TopicsTopicFactsRouteImport
      parentRoute: typeof TopicsTopicRoute
    }
    '/topics/$topic/evidence': {
      id: '/topics/$topic/evidence'
      path: '/evidence'
      fullPath: '/topics/$topic/evidence'
      preLoaderRoute: typeof TopicsTopicEvidenceRouteImport
      parentRoute: typeof TopicsTopicRoute
    }
    '/api/topics/$topic': {
      id: '/api/topics/$topic'
      path: '/$topic'
      fullPath: '/api/topics/$topic'
      preLoaderRoute: typeof ApiTopicsTopicRouteImport
      parentRoute: typeof ApiTopicsRoute
    }
    '/api/events/status': {
      id: '/api/events/status'
      path: '/status'
      fullPath: '/api/events/status'
      preLoaderRoute: typeof ApiEventsStatusRouteImport
      parentRoute: typeof ApiEventsRoute
    }
    '/api/adrs/$id': {
      id: '/api/adrs/$id'
      path: '/$id'
      fullPath: '/api/adrs/$id'
      preLoaderRoute: typeof ApiAdrsIdRouteImport
      parentRoute: typeof ApiAdrsRoute
    }
    '/topics/$topic/documents/$kind': {
      id: '/topics/$topic/documents/$kind'
      path: '/documents/$kind'
      fullPath: '/topics/$topic/documents/$kind'
      preLoaderRoute: typeof TopicsTopicDocumentsKindRouteImport
      parentRoute: typeof TopicsTopicRoute
    }
    '/api/topics/$topic/graph': {
      id: '/api/topics/$topic/graph'
      path: '/graph'
      fullPath: '/api/topics/$topic/graph'
      preLoaderRoute: typeof ApiTopicsTopicGraphRouteImport
      parentRoute: typeof ApiTopicsTopicRoute
    }
    '/api/topics/$topic/evidence': {
      id: '/api/topics/$topic/evidence'
      path: '/evidence'
      fullPath: '/api/topics/$topic/evidence'
      preLoaderRoute: typeof ApiTopicsTopicEvidenceRouteImport
      parentRoute: typeof ApiTopicsTopicRoute
    }
    '/api/topics/$topic/docs': {
      id: '/api/topics/$topic/docs'
      path: '/docs'
      fullPath: '/api/topics/$topic/docs'
      preLoaderRoute: typeof ApiTopicsTopicDocsRouteImport
      parentRoute: typeof ApiTopicsTopicRoute
    }
    '/api/topics/$topic/docs/$kind': {
      id: '/api/topics/$topic/docs/$kind'
      path: '/$kind'
      fullPath: '/api/topics/$topic/docs/$kind'
      preLoaderRoute: typeof ApiTopicsTopicDocsKindRouteImport
      parentRoute: typeof ApiTopicsTopicDocsRoute
    }
  }
}

interface ApiAdrsRouteChildren {
  ApiAdrsIdRoute: typeof ApiAdrsIdRoute
}

const ApiAdrsRouteChildren: ApiAdrsRouteChildren = {
  ApiAdrsIdRoute: ApiAdrsIdRoute,
}

const ApiAdrsRouteWithChildren =
  ApiAdrsRoute._addFileChildren(ApiAdrsRouteChildren)

interface ApiEventsRouteChildren {
  ApiEventsStatusRoute: typeof ApiEventsStatusRoute
}

const ApiEventsRouteChildren: ApiEventsRouteChildren = {
  ApiEventsStatusRoute: ApiEventsStatusRoute,
}

const ApiEventsRouteWithChildren = ApiEventsRoute._addFileChildren(
  ApiEventsRouteChildren,
)

interface ApiTopicsTopicDocsRouteChildren {
  ApiTopicsTopicDocsKindRoute: typeof ApiTopicsTopicDocsKindRoute
}

const ApiTopicsTopicDocsRouteChildren: ApiTopicsTopicDocsRouteChildren = {
  ApiTopicsTopicDocsKindRoute: ApiTopicsTopicDocsKindRoute,
}

const ApiTopicsTopicDocsRouteWithChildren =
  ApiTopicsTopicDocsRoute._addFileChildren(ApiTopicsTopicDocsRouteChildren)

interface ApiTopicsTopicRouteChildren {
  ApiTopicsTopicDocsRoute: typeof ApiTopicsTopicDocsRouteWithChildren
  ApiTopicsTopicEvidenceRoute: typeof ApiTopicsTopicEvidenceRoute
  ApiTopicsTopicGraphRoute: typeof ApiTopicsTopicGraphRoute
}

const ApiTopicsTopicRouteChildren: ApiTopicsTopicRouteChildren = {
  ApiTopicsTopicDocsRoute: ApiTopicsTopicDocsRouteWithChildren,
  ApiTopicsTopicEvidenceRoute: ApiTopicsTopicEvidenceRoute,
  ApiTopicsTopicGraphRoute: ApiTopicsTopicGraphRoute,
}

const ApiTopicsTopicRouteWithChildren = ApiTopicsTopicRoute._addFileChildren(
  ApiTopicsTopicRouteChildren,
)

interface ApiTopicsRouteChildren {
  ApiTopicsTopicRoute: typeof ApiTopicsTopicRouteWithChildren
}

const ApiTopicsRouteChildren: ApiTopicsRouteChildren = {
  ApiTopicsTopicRoute: ApiTopicsTopicRouteWithChildren,
}

const ApiTopicsRouteWithChildren = ApiTopicsRoute._addFileChildren(
  ApiTopicsRouteChildren,
)

interface TopicsTopicRouteChildren {
  TopicsTopicEvidenceRoute: typeof TopicsTopicEvidenceRoute
  TopicsTopicFactsRoute: typeof TopicsTopicFactsRoute
  TopicsTopicGraphRoute: typeof TopicsTopicGraphRoute
  TopicsTopicHealthRoute: typeof TopicsTopicHealthRoute
  TopicsTopicReceiptsRoute: typeof TopicsTopicReceiptsRoute
  TopicsTopicDocumentsKindRoute: typeof TopicsTopicDocumentsKindRoute
}

const TopicsTopicRouteChildren: TopicsTopicRouteChildren = {
  TopicsTopicEvidenceRoute: TopicsTopicEvidenceRoute,
  TopicsTopicFactsRoute: TopicsTopicFactsRoute,
  TopicsTopicGraphRoute: TopicsTopicGraphRoute,
  TopicsTopicHealthRoute: TopicsTopicHealthRoute,
  TopicsTopicReceiptsRoute: TopicsTopicReceiptsRoute,
  TopicsTopicDocumentsKindRoute: TopicsTopicDocumentsKindRoute,
}

const TopicsTopicRouteWithChildren = TopicsTopicRoute._addFileChildren(
  TopicsTopicRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAdrsRoute: ApiAdrsRouteWithChildren,
  ApiEventsRoute: ApiEventsRouteWithChildren,
  ApiFilesRoute: ApiFilesRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiOverviewRoute: ApiOverviewRoute,
  ApiTopicsRoute: ApiTopicsRouteWithChildren,
  TopicsTopicRoute: TopicsTopicRouteWithChildren,
  TopicsIndexRoute: TopicsIndexRoute,
  ApiIndexIndexRoute: ApiIndexIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
